###GET TEST
GET http://localhost:3001/api/blogs

###POST TEST
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "first2",
    "author": "berry",
    "url": "https://www.google.com/",
    "likes": 1
}
