##below are requests to notes
##GET http://localhost:3001/api/notes
##POST http://localhost:3001/api/notes

##below are requests to users

GET http://localhost:3001/api/notes
###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RQb3N0MyIsImlkIjoiNjQ1ZTg1OGQ1ZmVkNWE5MDljNWQwYzI1IiwiaWF0IjoxNjgzOTE2ODM5fQ.M7LoJt25dZeyuVojB79DOQTZB_s-QSq7r0ADUGMv8V0


{
    "content":"testing new note logged in 2",
    "important":true
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"testPost3",
    "password":"password3"
}