###GET TEST
GET http://localhost:3001/api/users

###POST TEST
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"Username3",
    "name":"name3",
    "password":"pass3"
}

