##below are requests to notes
##GET http://localhost:3001/api/notes
##POST http://localhost:3001/api/notes

##below are requests to users

GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
content-type:application/json

{
    "username":"testPost",
    "name":"testPostName",
    "password":"password"
}