###GET TEST
GET http://localhost:3001/api/blogs

###POST TEST
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjQ5OWIxZDFlYzhkMDY4NWU0ZjI1MThmIiwiaWF0IjoxNjg3Nzk2NDc1LCJleHAiOjE2ODc4MDAwNzV9.r3uP7YEWNa8aI1QX34-rzpqivQWF7fuI8BpdTY7zE4w

{
    "title": "testing a note post after login 1",
    "author": "login 1",
    "url": "https://www.google.com/",
    "likes": 2
}
###DELETE TEST ID OF BLOG IS NEEDED AFTER /
DELETE  http://localhost:3001/api/blogs/6499bb3df37e319ea0bcab0b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjQ5OWIxZDFlYzhkMDY4NWU0ZjI1MThmIiwiaWF0IjoxNjg3Nzk2NDc1LCJleHAiOjE2ODc4MDAwNzV9.r3uP7YEWNa8aI1QX34-rzpqivQWF7fuI8BpdTY7zE4w

###
PUT http://localhost:3001/api/blogs/6499bb4ff37e319ea0bcab1e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjQ5OWIxZDFlYzhkMDY4NWU0ZjI1MThmIiwiaWF0IjoxNjg3Nzk2NDc1LCJleHAiOjE2ODc4MDAwNzV9.r3uP7YEWNa8aI1QX34-rzpqivQWF7fuI8BpdTY7zE4w

{
    "title": "testing update",
    "author": "2",
    "url": "https://www.google.com/something",
    "likes": 1
}